// <auto-generated />
using System;
using FluentApiJunctionPayloadExamples.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluentApiJunctionPayloadExamples.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605231004_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FluentApiJunctionPayloadExamples.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FluentApiJunctionPayloadExamples.Models.PostTag", b =>
                {
                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Pid", "Tid");

                    b.HasIndex("Tid");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("FluentApiJunctionPayloadExamples.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FluentApiJunctionPayloadExamples.Models.PostTag", b =>
                {
                    b.HasOne("FluentApiJunctionPayloadExamples.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("Pid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluentApiJunctionPayloadExamples.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
